// OPERATIONS

export const GET_OPERATIONS = "GET_OPERATIONS";
export const GET_OPERATION = "GET_OPERATION";
export const CREATE_OPERATION = "CREATE_OPERATION";
export const UPDATE_OPERATION = "UPDATE_OPERATION";
export const DELETE_OPERATION = "DELETE_OPERATION";

// PATIENTS

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";